services:
  - type: web
    name: glucolog-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn glucose_prediction_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18




